version: '2'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

  telegram-notifier:
    build: tgnotifer
    network_mode: host

  resolver:
    build:
      context: .
      dockerfile: notifications.dockerfile
    network_mode: host
    ports:
      - '4005:4005'
  finances:
    build:
      context: .
      dockerfile: finances.dockerfile
    network_mode: host
    ports:
      - '4000:4000'
  auth:
    build:
      context: .
      dockerfile: auth.dockerfile
    network_mode: host
    ports:
      - '4001:4001'




volumes:
  dbdata6:
  cache:


